version = 0.1
[default.deploy.parameters]
stack_name = "matt-test"
resolve_s3 = true
s3_prefix = "matt-test"
region = "us-east-1"
profile = "CapstoneAdmin"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
