AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Disc Golf Collection Manager API

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs18.x
    MemorySize: 256
    Environment:
      Variables:
        TABLE_NAME: !Ref DiscCollectionTable
    CodeUri: src/functions/dist

Resources:
  DiscCollectionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: disc-collection
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: discId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: discId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  DiscCollectionApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"

  GetCollectionFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: getCollection.handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref DiscCollectionTable
      Events:
        GetCollection:
          Type: Api
          Properties:
            RestApiId: !Ref DiscCollectionApi
            Path: /collection
            Method: GET

  AddDiscFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: addDisc.handler
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref DiscCollectionTable
      Events:
        AddDisc:
          Type: Api
          Properties:
            RestApiId: !Ref DiscCollectionApi
            Path: /collection
            Method: POST

  UpdateDiscFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: updateDisc.handler
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref DiscCollectionTable
      Events:
        UpdateDisc:
          Type: Api
          Properties:
            RestApiId: !Ref DiscCollectionApi
            Path: /collection/{discId}
            Method: PUT

  RemoveDiscFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: removeDisc.handler
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref DiscCollectionTable
      Events:
        RemoveDisc:
          Type: Api
          Properties:
            RestApiId: !Ref DiscCollectionApi
            Path: /collection/{discId}
            Method: DELETE

  ToggleDiscInBagFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toggleDiscInBag.handler
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref DiscCollectionTable
      Events:
        ToggleDiscInBag:
          Type: Api
          Properties:
            RestApiId: !Ref DiscCollectionApi
            Path: /collection/{discId}/bag
            Method: PUT

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${DiscCollectionApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
